/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup Check */
        post: operations["setup_check_api_setup_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_resumes_get"];
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Resume */
        post: operations["extract_resume_api_resumes__resume_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Draft */
        get: operations["get_resume_draft_api_resumes__resume_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profiles__profile_id__get"];
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_profiles__profile_id__patch"];
        trace?: never;
    };
    "/api/profiles/{profile_id}/gap-fill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gap Fill Profile */
        post: operations["gap_fill_profile_api_profiles__profile_id__gap_fill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/search-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Search Queries */
        post: operations["regenerate_search_queries_api_profiles__profile_id__search_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job Search */
        post: operations["start_job_search_api_jobs_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Search Status */
        get: operations["get_job_search_status_api_jobs_searches__search_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/searches/{search_id}/postings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Search Postings */
        get: operations["get_job_search_postings_api_jobs_searches__search_id__postings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Source */
        post: operations["enable_source_api_sources__name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwardItem */
        AwardItem: {
            /** Title */
            title: string;
            /** Issuer */
            issuer?: string | null;
            /**
             * Issued Date
             * @description verbatim as written on the resume
             */
            issued_date?: string | null;
        };
        /** Body_upload_resume_api_resumes_post */
        Body_upload_resume_api_resumes_post: {
            /** File */
            file: string;
        };
        /** CertificationItem */
        CertificationItem: {
            /** Name */
            name: string;
            /** Issuer */
            issuer?: string | null;
            /** Issued Date */
            issued_date?: string | null;
        };
        /** ContactInfo */
        ContactInfo: {
            /** Full Name */
            full_name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Country
             * @description ISO 3166-1 alpha-2 code (lowercase), e.g. 'de', 'in', 'us'
             */
            country?: string | null;
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["SourceLink"][];
        };
        /** DraftProfileResponse */
        DraftProfileResponse: {
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            draft_profile: components["schemas"]["StructuredProfile"];
            /** Parse Version */
            parse_version: string;
            /**
             * Parsed At
             * Format: date-time
             */
            parsed_at: string;
            search_queries?: components["schemas"]["StoredSearchQueries"] | null;
        };
        /** EducationItem */
        EducationItem: {
            /** Institution */
            institution?: string | null;
            /** Degree */
            degree?: string | null;
            /** Field */
            field?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ExperienceItem */
        ExperienceItem: {
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Start Date
             * @description verbatim as written on the resume
             */
            start_date?: string | null;
            /**
             * End Date
             * @description verbatim as written on the resume
             */
            end_date?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /**
             * Bullets
             * @default []
             */
            bullets: string[];
        };
        /** ExtraSection */
        ExtraSection: {
            /**
             * Title
             * @description original resume section title: Awards, Publications, Languages, Volunteer, ...
             */
            title: string;
            /**
             * Entries
             * @description one entry per line/bullet, verbatim
             */
            entries: string[];
        };
        /** GapFillAppliedField */
        GapFillAppliedField: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** GapFillField */
        GapFillField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** GapFillMessage */
        GapFillMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** GapFillRequest */
        GapFillRequest: {
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["GapFillMessage"][];
        };
        /** GapFillResponse */
        GapFillResponse: {
            /** Reply */
            reply: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "complete";
            /** Missing Fields */
            missing_fields: components["schemas"]["GapFillField"][];
            /** Applied Fields */
            applied_fields: components["schemas"]["GapFillAppliedField"][];
            structured_profile: components["schemas"]["StructuredProfile"];
            revision?: components["schemas"]["RevisionSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: boolean;
            /** Llm Configured */
            llm_configured: boolean;
        };
        /** JobPostingSummary */
        JobPostingSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Company */
            company?: string | null;
            /** Url */
            url?: string | null;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Currency */
            currency?: string | null;
        };
        /** JobSearchRequest */
        JobSearchRequest: {
            /** Query */
            query?: string | null;
            /** Profile Id */
            profile_id?: string | null;
            /** Source Queries */
            source_queries?: {
                [key: string]: components["schemas"]["SourceQuerySpec"];
            } | null;
            /** Location */
            location?: string | null;
            /** Country */
            country: string;
            /**
             * Results Wanted
             * @default 50
             */
            results_wanted: number;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Sources */
            sources?: string[] | null;
        };
        /** JobSearchStartResponse */
        JobSearchStartResponse: {
            /**
             * Search Id
             * Format: uuid
             */
            search_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "partial" | "failed";
        };
        /** JobSearchStatusResponse */
        JobSearchStatusResponse: {
            /**
             * Search Id
             * Format: uuid
             */
            search_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "partial" | "failed";
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["SourceOutcome"][];
            matching?: components["schemas"]["MatchingOutcome"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobType
         * @enum {string}
         */
        JobType: "full_time" | "part_time" | "contract" | "internship" | "temporary";
        /** MatchResponse */
        MatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job_posting: components["schemas"]["JobPostingSummary"];
            /** Vector Score */
            vector_score: number;
            /** Role Fit */
            role_fit?: number | null;
            /** Company Fit */
            company_fit?: number | null;
            /** Final Score */
            final_score: number;
            /** Rationale */
            rationale?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MatchingOutcome */
        MatchingOutcome: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed" | "skipped";
            /**
             * Scored Count
             * @default 0
             */
            scored_count: number;
            /**
             * Rationale Count
             * @default 0
             */
            rationale_count: number;
            /**
             * Rerank Prompt Tokens
             * @default 0
             */
            rerank_prompt_tokens: number;
            /**
             * Rerank Completion Tokens
             * @default 0
             */
            rerank_completion_tokens: number;
            /** Warning */
            warning?: string | null;
        };
        /** Preferences */
        Preferences: {
            /** Target Title */
            target_title?: string | null;
            /** Target Location */
            target_location?: string | null;
            /** Remote Preference */
            remote_preference?: ("remote" | "hybrid" | "onsite" | "flexible") | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Currency */
            currency?: string | null;
            /** Seniority */
            seniority?: ("intern" | "junior" | "mid" | "senior" | "staff" | "lead" | "principal" | "manager" | "director" | "executive") | null;
            /** Work Authorization */
            work_authorization?: string | null;
        };
        /** ProfileCreate */
        ProfileCreate: {
            /** Name */
            name: string;
            structured_profile: components["schemas"]["StructuredProfile"];
            /**
             * Source Resume Id
             * @description resume whose AI draft this profile is created from
             */
            source_resume_id?: string | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Name */
            name: string;
            structured_profile: components["schemas"]["StructuredProfile"];
            search_queries?: components["schemas"]["StoredSearchQueries"] | null;
            /** Source Resume Id */
            source_resume_id: string | null;
            /** Source Resume Filename */
            source_resume_filename: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            last_revision?: components["schemas"]["RevisionSummary"] | null;
        };
        /** ProfileSummary */
        ProfileSummary: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Name */
            name: string;
            /** Source Resume Filename */
            source_resume_filename: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Name */
            name?: string | null;
            structured_profile?: components["schemas"]["StructuredProfile"] | null;
            /**
             * Source Resume Id
             * @description resume whose AI draft this save is reviewed from
             */
            source_resume_id?: string | null;
        };
        /** ProjectItem */
        ProjectItem: {
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Start Date
             * @description verbatim as written on the resume
             */
            start_date?: string | null;
            /**
             * End Date
             * @description verbatim as written on the resume
             */
            end_date?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Bullets
             * @default []
             */
            bullets: string[];
            /**
             * Technologies
             * @default []
             */
            technologies: string[];
        };
        /**
         * RemoteType
         * @enum {string}
         */
        RemoteType: "remote" | "hybrid" | "on_site";
        /** ResumeSummaryResponse */
        ResumeSummaryResponse: {
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at: string | null;
            /** Parse Version */
            parse_version: string | null;
            /** Has Draft */
            has_draft: boolean;
            /** Source Profile Names */
            source_profile_names: string[];
        };
        /** ResumeUploadResponse */
        ResumeUploadResponse: {
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Extracted Text */
            extracted_text: string;
            /** Page Count */
            page_count: number | null;
            /**
             * Parsed At
             * Format: date-time
             */
            parsed_at: string;
            /** Parse Version */
            parse_version: string;
        };
        /** RevisionSummary */
        RevisionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "ai_extraction" | "manual_edit" | "gap_fill" | "reupload_merge";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchQueriesResponse */
        SearchQueriesResponse: {
            /** Queries */
            queries: {
                [key: string]: components["schemas"]["SourceQuerySpec"];
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generated By */
            generated_by: string;
        };
        /** SearchQueryGenerateRequest */
        SearchQueryGenerateRequest: {
            /** Sources */
            sources?: string[] | null;
        };
        /** SetupCheckResponse */
        SetupCheckResponse: {
            /** Llm Configured */
            llm_configured: boolean;
            /** Embedding Configured */
            embedding_configured: boolean;
            /** Adzuna Configured */
            adzuna_configured: boolean;
            /** Apify Configured */
            apify_configured: boolean;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** SourceEnableRequest */
        SourceEnableRequest: {
            /**
             * Acknowledged Disclosure
             * @default false
             */
            acknowledged_disclosure: boolean;
        };
        /** SourceInfoResponse */
        SourceInfoResponse: {
            /** Name */
            name: string;
            /** Is Official Api */
            is_official_api: boolean;
            /** Disclosure Required */
            disclosure_required: boolean;
            /** Is Configured */
            is_configured: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Supports Exclusions
             * @default false
             */
            supports_exclusions: boolean;
        };
        /** SourceLink */
        SourceLink: {
            /**
             * Label
             * @description e.g. LinkedIn, GitHub, portfolio
             */
            label?: string | null;
            /** Url */
            url: string;
        };
        /** SourceOutcome */
        SourceOutcome: {
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed" | "skipped";
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Warning */
            warning?: string | null;
        };
        /** SourceQuerySpec */
        SourceQuerySpec: {
            /** Title */
            title?: string | null;
            /** Skills */
            skills?: string[] | null;
            /** Exclude */
            exclude?: string[] | null;
            /** Query */
            query?: string | null;
        };
        /** StoredSearchQueries */
        StoredSearchQueries: {
            /** Queries */
            queries: {
                [key: string]: components["schemas"]["SourceQuerySpec"];
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generated By */
            generated_by: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /** StructuredProfile */
        StructuredProfile: {
            contact: components["schemas"]["ContactInfo"];
            /** Headline */
            headline?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Experience
             * @default []
             */
            experience: components["schemas"]["ExperienceItem"][];
            /**
             * Projects
             * @default []
             */
            projects: components["schemas"]["ProjectItem"][];
            /**
             * Education
             * @default []
             */
            education: components["schemas"]["EducationItem"][];
            /**
             * Certifications
             * @default []
             */
            certifications: components["schemas"]["CertificationItem"][];
            /**
             * Awards
             * @default []
             */
            awards: components["schemas"]["AwardItem"][];
            /**
             * Extra Sections
             * @default []
             */
            extra_sections: components["schemas"]["ExtraSection"][];
            preferences?: components["schemas"]["Preferences"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    setup_check_api_setup_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupCheckResponse"];
                };
            };
        };
    };
    list_resumes_api_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSummaryResponse"][];
                };
            };
        };
    };
    upload_resume_api_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_resume_api_resumes__resume_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_draft_api_resumes__resume_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    create_profile_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_profiles__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gap_fill_profile_api_profiles__profile_id__gap_fill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapFillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapFillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_search_queries_api_profiles__profile_id__search_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SearchQueryGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchQueriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_search_api_jobs_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_search_status_api_jobs_searches__search_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_search_postings_api_jobs_searches__search_id__postings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPostingSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfoResponse"][];
                };
            };
        };
    };
    enable_source_api_sources__name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceEnableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_matches_get: {
        parameters: {
            query: {
                location?: string | null;
                remote_type?: components["schemas"]["RemoteType"] | null;
                job_type?: components["schemas"]["JobType"] | null;
                posted_within_days?: number | null;
                profile_id: string;
                sort?: "final_score" | "vector_score" | "posted_at";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
